### ISSUE TITLE
ParseError: syntax error, unexpected 'version'

### ISSUE THREAD

**Issue by thshiro** [Nimut/phpunit-merger#18]
I'm getting an error when I try to run the following command:
```shell
phpdbg -qrr -d memory_limit=-1 vendor/bin/phpunit-merger coverage ./coverage
```

```shell
ParseError: syntax error, unexpected 'version' (T_STRING) in /var/www/src/coverage/phpunit-coverage-v2-groups.xml:1
Stack trace:
#0 /var/www/src/vendor/symfony/console/Command/Command.php(299): Nimut\PhpunitMerger\Command\CoverageCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/src/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/src/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand(Object(Nimut\PhpunitMerger\Command\CoverageCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/src/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/src/vendor/nimut/phpunit-merger/bin/phpunit-merger(29): Symfony\Component\Console\Application->run()
#5 {main}
```

I have multiple .xml files generated from phpunit coverage. I'm not running with xdebug mode, I use phpdbg:

```shell
phpdbg -qrr -d memory_limit=-1 vendor/bin/phpunit modules/ --configuration phpunit.xml --coverage-clover ./coverage/phpunit-coverage-v2-groups.xml --coverage-html ./public/coverage/
```

I've tried with xdebug without phpdbg and I get the same error. Also tried with php ^7.4 and phpunit ^9

My current php version is ^7.3 and phpunit ^8.5.

Can anyone help me here? Thanks!

**Comment by thshiro** [comment]
Nevermind. I was generating the coverage with `--coverage-clover` instead `--coverage-php`. At least I'm not getting the error now. It seems to be merging fine.

But I noticed that when I generate the html with the phpunit-merger command, I have a different coverage (%) than the phpunit normal command shows. I will test more. If anyone can help me with this one, comment here, otherwise, we can close this issue. ;)

**Comment by thshiro** [comment]
About the last comment, the difference was because the phpunit config file was including all the directories instead one.
